name: Bedrock Server CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: 
      - master

jobs:
  ci_build_container:
    name: Build and test container
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build ./container --tag aessing/minecraft-bedrock:latest
      
    - name: Test create-BedrockContainer.sh and run the container
      run: create-BedrockContainer.sh --server-name "GitHub Container CI" --server-port 19132 --server-portv6 19133 --level-name "Container CI World"
      working-directory: ./scripts
      #run: docker run -d -i -t --rm --restart no --network=host -e PORTv4=19132 -e PORTv6=19133 -e WORLD='CiTestWorld' --name='CiTestContainer' minecraft-bedrock-server:ci-build
    
    - name: Wait a few seconds for the container to get runnung or fail
      run: sleep 30s
  
    - name: Check if Docker container is up and running
      run: if ! [ "$( docker container inspect -f '{{.State.Status}}' Container_CI_World )" == "running" ]; then exit 1; fi
