name: Container CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build ./container --tag minecraft-bedrock-server:ci-build
      
    - name:  Run the Docker image
      run: docker run -d -i -t --rm --restart no --network=host -e PORTv4=19132 -e PORTv6=19133 -e WORLD='CiTestWorld' --name='CiTestContainer' minecraft-bedrock-server:ci-build
    
    - name: Check if Docker container is running
      run: |
        sleep 30s
        if ! [ "$( docker container inspect -f '{{.State.Status}}' CiTestContainer )" == "running" ]; then exit 1; fi
  
